First release PR -- reviews wanted :)
nf-core/ddamsproteomics pull request #5
Opened 2018-11-28 10:53 UTC by glormph

Many thanks to contributing to nf-core/ddamsproteomics!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [ ] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/ddamsproteomics branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/ddamsproteomics)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [X] Make sure your code lints (`nf-core lint .`).
 - [X] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [X] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/ddamsproteomics/tree/master/.github/CONTRIBUTING.md

First release PR. The whole pipeline lints and tests run fine *on the dev branch*.

I havent gotten my head around how the combination of `bump-version` and linting decides about the container definition, but `bump-version` did not accept `nfcore/ddamsproteomics:dev` which had to be changed to `latest` before it actually bumped it to 1.0.0. Hence travis will not checkout since the `latest` container is based off this repo's `master` branch and that is behind.

But now I'd like to learn from the mistakes I've made, so bring on the reviews. :)

2018-11-29 02:45 UTC, likelet commented
I thinks you may have a logo first

2018-12-06 08:57 UTC, apeltzer requested changes
Please document the code much more :-)

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +// Parse input variables values
This needs more explicit details: What is happening here? Is this a set of defaults but can be set by users?

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +setdenoms = [:]
Same here...

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +massshift = [tmt:0.0013, itraq:0.00125, false:0][plextype]
Setting these values as defaults or can they be set by users?

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +summary['Do not quantify'] = params.noquant
Nice!

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +  .map { it -> [file(it[0]), it[1], it[2] ? it[2] : it[1], it[3] ? it[3] : 'NA' ]} // create file, set plate to setname, and fraction to NA if there is none
Need a bit more verbose code documentation here: Hard to understand why you do it this way..!

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +isobaricxml
More documentation please!!!

2018-12-06 08:57 UTC, apeltzer commented on main.nf
> +kronik_out
More documentation please!!!

2018-12-17 14:22 UTC, glormph commented
Thanks for the comments @apeltzer! :)

2019-01-07 15:36 UTC, glormph commented
I assume I need to do a lot more, but unsure what?

2019-01-07 16:17 UTC, apeltzer commented
I'll have a look later :-)

2019-01-07 19:03 UTC, apeltzer requested changes
Some comments from my side: Mostly documentation++ ;-)

2019-01-07 19:03 UTC, apeltzer commented on nextflow.config
> +  fixOwnership = true
Indentation fix?

2019-01-07 19:03 UTC, apeltzer commented on nextflow.config
> +  runOptions = "-u \$(id -u):\$(id -g)"
Same here

2019-01-07 19:03 UTC, apeltzer commented on bin/scrape_software_versions.py
> +    'nf-core/ddamsproteomics': ['v_pipeline.txt', r"(\S+)"],
Maybe add your software dependencies in here as well?

2019-01-07 19:03 UTC, apeltzer commented on main.nf
> +  cp $hkconf config
This looks a bit weird to me: The $hkconf is already staged by Nextflow in the process specific work directory - no need to copy anything here...

If you need the content in a separate file, you could still do a simple `cat $hkconfig > config` here...

2019-01-07 19:03 UTC, apeltzer commented on main.nf
> +  kronik -c 5 -d 3 -g 1 -m 8000 -n 600 -p 10 hardklor.out ${sample}.kr
And maybe explain a little what you're doing here :-)

2019-01-07 19:03 UTC, apeltzer commented on main.nf
> +  cp lookup psmlookup
`cat lookup > psmlookup` is more explanatory for users checking this code here 👍 

If you don't need the file as an extra one - just use $lookup in the next steps...

2019-01-07 19:03 UTC, apeltzer commented on main.nf
> +  mv psmlookup ${td}_psmlookup.sql
You could use nextflows file renaming functionality to put this into a channel with a different name, thus not needing this...

2019-01-07 19:03 UTC, apeltzer commented on main.nf
> +  msspeptable psm2pep -i psms -o peptides --scorecolpattern svm --spectracol 1 ${!params.noquant && params.isobaric && td == 'target' ? "--isobquantcolpattern plex" : "" } ${!params.noquant ? "--ms1q
This needs more comments!!

2019-01-07 19:03 UTC, apeltzer commented on main.nf
> +  tail -n+2 psms|cut -f ${accolmap.proteins}|grep -v '\\;'|grep -v "^\$"|sort|uniq >> proteins
Especially this part - I get what the command does, but *why* you are doing this isn't clear to me :-)

2019-01-09 11:26 UTC, glormph commented
Answered the questions :)

2019-01-22 14:34 UTC, glormph commented
Ping this PR. Do I need to do anything specific for the review somewhere on github? Or are commits enough? Due to requests from the lab I'm preparing updates for version 1.1 already :)

2019-01-22 14:44 UTC, apeltzer commented
There are some errors in the CI:

```
ERROR: Test Failures:
  http://nf-co.re/errors#5: CI is not pulling the correct docker image. Should be:
    'docker pull nfcore/ddamsproteomics:dev'
  http://nf-co.re/errors#5: CI is not tagging docker image correctly. Should be:
    'docker tag nfcore/ddamsproteomics:dev nfcore/ddamsproteomics:1.0.0'
```

and here:

```
ERROR ~ Error executing process > 'msgfPlus (1)'
Caused by:
  Process `msgfPlus (1)` terminated with an error exit status (1)
Command executed:
  msgf_plus -Xmx16G -d db.fa -s set1_518_scans_QE_tmt10_fasp_cellines_human.mzML -o "set1_518_scans_QE_tmt10_fasp_cellines_human.mzid" -thread 12 -mod tmtmods.txt -tda 0 -t 10.0ppm -ti -1,2 -m 0 -inst 3 -e 1 -protocol 4 -ntt 2 -minLength 7 -maxLength 50 -minCharge 2 -maxCharge 6 -n 1 -addFeatures 1
  msgf_plus -Xmx3500M edu.ucsd.msjava.ui.MzIDToTsv -i "set1_518_scans_QE_tmt10_fasp_cellines_human.mzid" -o out.mzid.tsv
  rm db.c*
Command exit status:
  1
Command output:
  MS-GF+ Release (v2017.07.21) (21 July 2017)
  Loading database files...
  Warning: Sequence database contains 134 counts of letter 'B', which does not correspond to an amino acid.
  Warning: Sequence database contains 116 counts of letter 'U', which does not correspond to an amino acid.
  Warning: Sequence database contains 15124 counts of letter 'X', which does not correspond to an amino acid.
  Warning: Sequence database contains 128 counts of letter 'Z', which does not correspond to an amino acid.
  Creating the suffix array indexed file... Size: 67914521
  AlphabetSize: 28
  Suffix creation: 0.00% complete.
  Suffix creation: 14.72% complete.
  Suffix creation: 29.45% complete.
  Suffix creation: 44.17% complete.
  Suffix creation: 58.90% complete.
  Suffix creation: 73.62% complete.
  Suffix creation: 88.35% complete.
  Sorting 0.00% complete.
  Sorting 5.81% complete.
  Sorting 11.62% complete.
  Sorting 17.43% complete.
  Sorting 23.24% complete.
  Sorting 29.05% complete.
  Sorting 34.86% complete.
  Sorting 40.67% complete.
  Sorting 46.48% complete.
  Sorting 52.29% complete.
  Sorting 58.10% complete.
  Sorting 63.91% complete.
  Sorting 69.73% complete.
  Sorting 75.54% complete.
  Sorting 81.35% complete.
  Sorting 87.16% complete.
  Sorting 92.97% complete.
  Sorting 98.78% complete.
  Loading database finished (elapsed time: 65.32 sec)
  Reading spectra...
Command error:
  Exception in thread "main" java.lang.ExceptionInInitializerError
  	at uk.ac.ebi.jmzml.xml.Constants.<clinit>(Constants.java:56)
  	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:82)
  	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory$MzMlIndexerImpl.<init>(MzMLIndexerFactory.java:52)
  	at uk.ac.ebi.jmzml.xml.xxindex.MzMLIndexerFactory.buildIndex(MzMLIndexerFactory.java:49)
  	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:121)
  	at uk.ac.ebi.jmzml.xml.io.MzMLUnmarshaller.<init>(MzMLUnmarshaller.java:100)
  	at edu.ucsd.msjava.mzml.MzMLAdapter.<init>(MzMLAdapter.java:27)
  	at edu.ucsd.msjava.msutil.SpectraAccessor.getSpecMap(SpectraAccessor.java:38)
  	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:217)
  	at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:105)
  	at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:56)
  Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.JAXBException
   - with linked exception:
  [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
  	at javax.xml.bind.JAXB.unmarshal(JAXB.java:186)
  	at uk.ac.ebi.jmzml.MzMLElement.loadProperties(MzMLElement.java:609)
  	at uk.ac.ebi.jmzml.MzMLElement.<init>(MzMLElement.java:564)
  	at uk.ac.ebi.jmzml.MzMLElement.<clinit>(MzMLElement.java:83)
  	... 11 more
  Caused by: javax.xml.bind.JAXBException
   - with linked exception:
  [java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
  	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)
  	at javax.xml.bind.ContextFinder.find(ContextFinder.java:455)
  	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
  	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
  	at javax.xml.bind.JAXB$Cache.<init>(JAXB.java:127)
  	at javax.xml.bind.JAXB.getContext(JAXB.java:154)
  	at javax.xml.bind.JAXB.unmarshal(JAXB.java:183)
  	... 14 more
  Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  	at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:573)
  	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)
  	... 20 more
Work dir:
  /home/travis/build/nf-core/ddamsproteomics/tests/work/bd/12fa5ba21144f0aa579d9134e16822
```

2019-01-22 14:45 UTC, apeltzer commented
I think pinging @ewels @MaxUlysse for some reviews other than just me would be good 👍

2019-01-22 15:24 UTC, glormph commented
Whoa I didnt know you were the only one being pinged, sorry. Will ask some questions in slack.

2019-01-22 15:30 UTC, apeltzer commented
No worries Jorrit, I don't know whether the others know this PR would be nice for review 👍 So just thought to link them in here at some point now :-)

2019-01-22 16:23 UTC, ewels commented
I prefer to do a release PR on a pseudo-PR against the first commit, to see all of the code instead of just the changes in this review.

If you're done here @apeltzer then I suggest we merge into master and then set up a PR against the first commit as we've done in the other release-ready pipelines recently..

2019-01-22 16:23 UTC, ewels commented
...but I guess we're not done here yet as there are quite a few outstanding comments and tests are failing. So only when this is all resolved :)

2019-01-22 19:46 UTC, apeltzer commented
Yeah, some issues are still left and/or non-addressed, once this is done I guess we can proceed to do a full review prior to the first release 👍

2019-01-23 13:24 UTC, apeltzer approved these changes

2019-01-23 13:24 UTC, apeltzer commented
Please wait until the last test runs through, then feel free to merge it to master and open the pseudo PR to have others also check what's going on in the pipeline. 

I will also go through things then again 👍

2019-01-23 14:13 UTC, merged